# Generated by Django 3.2.6 on 2021-08-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('alphacode2', models.CharField(blank=True, max_length=2, null=True)),
                ('capital', models.CharField(blank=True, max_length=15, null=True)),
                ('population', models.CharField(blank=True, max_length=15, null=True)),
                ('timezone', models.CharField(blank=True, max_length=15, null=True)),
                ('flag_url', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='NeighbourCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(blank=True, max_length=15, null=True)),
                ('nlanguages', models.CharField(blank=True, max_length=15, null=True)),
                ('ncountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncountry', to='country_app.countries')),
            ],
        ),
    ]
