# Generated by Django 3.2.6 on 2021-08-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('alphacode2', models.CharField(blank=True, max_length=2, null=True)),
                ('capital', models.CharField(blank=True, max_length=15, null=True)),
                ('population', models.CharField(blank=True, max_length=15, null=True)),
                ('timezone', models.CharField(blank=True, max_length=2, null=True)),
                ('flag_url', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.CharField(blank=True, max_length=250, null=True)),
                ('neighbouring_countries', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
