# Generated by Django 3.2.6 on 2021-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='alphacode2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
