# Generated by Django 3.2.6 on 2021-08-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0002_alter_countries_alphacode2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='alphacode2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='timezone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
